version: "3.9"

services:
  database_guAPI:
    image: postgres
    container_name: database_guAPI
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=gurental
      - POSTGRES_DB=rental
    volumes:
      - pgdata:/data/postgres
    # network_mode: host
  app:
    build: .
    container_name: rental
    ports:
      - 3333:3333
    volumes:
      - .:/user/app
    # network_mode: host


volumes:
  pgdata:
    driver: local